// src/services/prompt-factory.ts
// 这是一个完整的模块，包含了所有步骤的Prompt生成逻辑

const getTypeScriptDefinition = (typeName: string): string => {
    const definitions: Record<string, string> = {
        StructuredData: `type CompanyInfo = { name: string; description: string; industry: string; }; type Product = { name: string; slug: string; category: string; short_description: string; keywords: string[]; }; type SellingPoints = { primary: string; secondary: string; tertiary: string; }; type TargetAudience = { region: string; industry: string; concerns: string[]; preference: string; }; type Assets = { images: Record<string, string>; }; type SEO = { mainKeywords: string[]; longTailKeywords: string[]; }; type StructuredData = { companyInfo: CompanyInfo; products: Product[]; sellingPoints: SellingPoints; targetAudience: TargetAudience; assets: Assets; seo: SEO; };`,
        DesignSystem: `type Palette = { primary: string; secondary: string; accent: string; text_on_dark: string; text_on_light: string; background_light: string; background_medium: string; background_dark: string; }; type Typography = { font_family_heading: string; font_family_body: string; }; type DesignSystem = { palette: Palette; typography: Typography; };`,
        WebsiteArchitecture: `type MenuItem = { name: string; path: string; }; type Header = { menuItems: MenuItem[]; }; type Footer = { sections: string[]; }; type GlobalElements = { header: Header; footer: Footer; }; type Page = { name: string; path: string; purpose: string; }; type WebsiteArchitecture = { globalElements: GlobalElements; pages: Page[]; };`,
        PageOutline: `type SEOInfo = { title: string; description: string; primaryKeyword: string; secondaryKeywords: string[]; }; type OutlineSection = { sectionName: string; instruction: string; }; type UpdatedPage = { name: string; path: string; purpose: string; seo: SEOInfo; outline: OutlineSection[]; };`,
        BlockLayout: `type ContentSource = { source: string; } | { text: string; } | { prompt: string; }; type Block = { component: string; level?: number; config?: Record<string, any>; props?: Record<string, any>; children?: Block[]; content?: ContentSource; };`
    };
    return definitions[typeName] || '';
};

export default {
  getStep1AnalyzerPrompt: (rawInput: string): string => `角色: 你是一位专业的商业分析师和市场策略顾问。\n背景: 我们正在启动一个AI驱动的网站生成项目。你的任务是将用户提供的非结构化公司介绍，转化为一份精确、完整、结构化的JSON数据档案。\n目标: 通读并理解下方提供的[用户输入文本]，并严格按照下方提供的TypeScript类型定义，将所有提炼出的信息组织成一个完整的JSON对象。\n约束与规则: 所有输出字段必须存在，不得遗漏。所有描述性文本都应使用专业、精炼的B2B商业语境。slug字段需全小写，用连字符'-'替换空格。\n输出类型定义 (TypeScript):\n${getTypeScriptDefinition('StructuredData')}\n\n[用户输入文本]:\n${rawInput}`,
  getStep2DesignerPrompt: (context: { industry: string; preference: string }): string => `角色: 你是一名经验丰富的品牌视觉设计师和用户体验(UX)专家。\n背景: 我们正在为一个工业LED照明制造商设计网站。根据初步分析，该公司的行业是"${context.industry}"，其目标客户偏好"${context.preference}"。\n目标: 创建一套专业、和谐且实用的全局视觉设计系统(designSystem.json)，统一网站所有页面的颜色和字体。\n输出类型定义 (TypeScript):\n${getTypeScriptDefinition('DesignSystem')}`,
  getStep3ArchitectPrompt: (context: { companyName: string; products: { name: string }[] }): string => `角色: 你是一名资深的网站信息架构师(IA)和用户体验策略师。\n背景: 基于已有的公司和产品数据，我们需要为这个外贸B2B网站规划一个清晰、直观、符合行业惯例的网站地图和全局导航元素。\n目标: 设计一个能够有效引导访客、展示核心信息并促进商业咨询的网站结构。\n输出类型定义 (TypeScript):\n${getTypeScriptDefinition('WebsiteArchitecture')}`,
  getStep4PlannerPrompt: (blueprintV1: any): string => `角色: 你是一位集B2B内容营销、搜索引擎优化(SEO)和用户旅程规划于一身的顶级内容策略专家。\n背景: 现在我们有了完整的网站蓝图，它包含了业务数据、设计系统和页面结构。下一步是为蓝图中的每个页面注入生命力——规划其具体内容和SEO策略。\n目标: 遍历输入数据中pages数组的每一个页面对象，并为其精心策划seo信息和outline内容大纲。\n详细任务: 遍历页面，规划SEO信息(title, description, keywords)，规划内容大纲(outline)，将页面内容分解为若干个有逻辑顺序的内容区块(Section)，并为每个区块撰写清晰的instruction指令。\n输出类型定义 (TypeScript):\n${getTypeScriptDefinition('PageOutline')}\n\n[输入蓝图 V1]:\n${JSON.stringify(blueprintV1, null, 2)}`,
  getStep5LayoutPrompt: (pageOutline: any, blockLibrary: any): string => `角色: 你是一名顶级的WordPress古腾堡技术架构师和前端设计师。\n背景: 你收到了一份来自"内容策略师"的页面大纲(outline)。你还有一个严格定义的"可用区块库"。\n目标: 将自然语言的"意图"，精确地"翻译"成一个严格结构化的JSON布局指令。将每一个instruction都转换成一个或多个嵌套的Block对象。\n约束: 只能从下方提供的"可用区块库"中选择区块，绝不能发明。必须严格遵循自定义区块"说明书(Manifest)"中定义的props结构。所有需要AI生成文本的地方，必须以{"prompt": "..."}的形式标记。\n输出类型定义 (TypeScript):\n${getTypeScriptDefinition('BlockLayout')}\n\n[可用区块库]:\n${JSON.stringify(blockLibrary, null, 2)}\n\n[页面大纲]:\n${JSON.stringify(pageOutline, null, 2)}`,
  getStep5_5CopywriterPrompt: (companyContext: any, taskList: Record<string, string>): string => `角色: 你是一名顶级的B2B外贸网站文案专家。\n背景: 整个网站的结构和布局已经设计完成。\n目标: 为"文案生成任务列表"中的每一个任务ID，生成一段高质量的、符合其语境和要求的文案。\n约束与规则: 语调应专业、自信、直接。严格按照要求的{ "任务ID": "生成的文案" } JSON格式返回结果，不要添加任何额外的解释或对话。\n\n公司上下文:\n${JSON.stringify(companyContext, null, 2)}\n\n文案生成任务列表:\n${JSON.stringify(taskList, null, 2)}`,
};
